//
// AcceptContract200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AcceptContract200ResponseData: Codable, JSONEncodable, Hashable {

    public var agent: AnyCodable
    public var contract: AnyCodable

    public init(agent: AnyCodable, contract: AnyCodable) {
        self.agent = agent
        self.contract = contract
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agent
        case contract
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agent, forKey: .agent)
        try container.encode(contract, forKey: .contract)
    }
}

