//
// CreateShipSystemScan201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateShipSystemScan201ResponseData: Codable, JSONEncodable, Hashable {

    public var cooldown: AnyCodable
    public var systems: [AnyCodable]

    public init(cooldown: AnyCodable, systems: [AnyCodable]) {
        self.cooldown = cooldown
        self.systems = systems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cooldown
        case systems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cooldown, forKey: .cooldown)
        try container.encode(systems, forKey: .systems)
    }
}

