//
// CreateShipWaypointScan201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateShipWaypointScan201ResponseData: Codable, JSONEncodable, Hashable {

    public var cooldown: AnyCodable
    public var waypoints: [AnyCodable]

    public init(cooldown: AnyCodable, waypoints: [AnyCodable]) {
        self.cooldown = cooldown
        self.waypoints = waypoints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cooldown
        case waypoints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cooldown, forKey: .cooldown)
        try container.encode(waypoints, forKey: .waypoints)
    }
}

