//
// DeliverContractRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliverContractRequest: Codable, JSONEncodable, Hashable {

    public var shipSymbol: String
    public var tradeSymbol: String
    public var units: Int

    public init(shipSymbol: String, tradeSymbol: String, units: Int) {
        self.shipSymbol = shipSymbol
        self.tradeSymbol = tradeSymbol
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shipSymbol
        case tradeSymbol
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shipSymbol, forKey: .shipSymbol)
        try container.encode(tradeSymbol, forKey: .tradeSymbol)
        try container.encode(units, forKey: .units)
    }
}

