//
// ExtractResourcesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtractResourcesRequest: Codable, JSONEncodable, Hashable {

    public var survey: AnyCodable?

    public init(survey: AnyCodable? = nil) {
        self.survey = survey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case survey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(survey, forKey: .survey)
    }
}

