//
// ExtractResources201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtractResources201ResponseData: Codable, JSONEncodable, Hashable {

    public var cooldown: AnyCodable
    public var extraction: AnyCodable
    public var cargo: AnyCodable

    public init(cooldown: AnyCodable, extraction: AnyCodable, cargo: AnyCodable) {
        self.cooldown = cooldown
        self.extraction = extraction
        self.cargo = cargo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cooldown
        case extraction
        case cargo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cooldown, forKey: .cooldown)
        try container.encode(extraction, forKey: .extraction)
        try container.encode(cargo, forKey: .cargo)
    }
}

