//
// JumpShipRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JumpShipRequest: Codable, JSONEncodable, Hashable {

    /** The system symbol to jump to. */
    public var systemSymbol: String

    public init(systemSymbol: String) {
        self.systemSymbol = systemSymbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case systemSymbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(systemSymbol, forKey: .systemSymbol)
    }
}

