//
// JumpShip200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JumpShip200ResponseData: Codable, JSONEncodable, Hashable {

    public var cooldown: AnyCodable
    public var nav: AnyCodable?

    public init(cooldown: AnyCodable, nav: AnyCodable? = nil) {
        self.cooldown = cooldown
        self.nav = nav
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cooldown
        case nav
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cooldown, forKey: .cooldown)
        try container.encodeIfPresent(nav, forKey: .nav)
    }
}

