//
// OrbitShip200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrbitShip200ResponseData: Codable, JSONEncodable, Hashable {

    public var nav: AnyCodable

    public init(nav: AnyCodable) {
        self.nav = nav
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nav
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nav, forKey: .nav)
    }
}

