//
// PatchShipNavRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchShipNavRequest: Codable, JSONEncodable, Hashable {

    public var flightMode: AnyCodable?

    public init(flightMode: AnyCodable? = nil) {
        self.flightMode = flightMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case flightMode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(flightMode, forKey: .flightMode)
    }
}

