//
// Register201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Register201ResponseData: Codable, JSONEncodable, Hashable {

    public var agent: AnyCodable
    public var contract: AnyCodable
    public var faction: AnyCodable
    public var ship: AnyCodable
    /** A Bearer token for accessing secured API endpoints. */
    public var token: String

    public init(agent: AnyCodable, contract: AnyCodable, faction: AnyCodable, ship: AnyCodable, token: String) {
        self.agent = agent
        self.contract = contract
        self.faction = faction
        self.ship = ship
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agent
        case contract
        case faction
        case ship
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agent, forKey: .agent)
        try container.encode(contract, forKey: .contract)
        try container.encode(faction, forKey: .faction)
        try container.encode(ship, forKey: .ship)
        try container.encode(token, forKey: .token)
    }
}

