//
// SellCargo201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SellCargo201ResponseData: Codable, JSONEncodable, Hashable {

    public var agent: AnyCodable
    public var cargo: AnyCodable
    public var transaction: AnyCodable

    public init(agent: AnyCodable, cargo: AnyCodable, transaction: AnyCodable) {
        self.agent = agent
        self.cargo = cargo
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agent
        case cargo
        case transaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agent, forKey: .agent)
        try container.encode(cargo, forKey: .cargo)
        try container.encode(transaction, forKey: .transaction)
    }
}

