//
// ShipRefine200ResponseDataProducedInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShipRefine200ResponseDataProducedInner: Codable, JSONEncodable, Hashable {

    public var tradeSymbol: String?
    public var units: Int?

    public init(tradeSymbol: String? = nil, units: Int? = nil) {
        self.tradeSymbol = tradeSymbol
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tradeSymbol
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tradeSymbol, forKey: .tradeSymbol)
        try container.encodeIfPresent(units, forKey: .units)
    }
}

