//
// TransferCargoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransferCargoRequest: Codable, JSONEncodable, Hashable {

    public var tradeSymbol: String
    public var units: Int
    public var shipSymbol: String

    public init(tradeSymbol: String, units: Int, shipSymbol: String) {
        self.tradeSymbol = tradeSymbol
        self.units = units
        self.shipSymbol = shipSymbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tradeSymbol
        case units
        case shipSymbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tradeSymbol, forKey: .tradeSymbol)
        try container.encode(units, forKey: .units)
        try container.encode(shipSymbol, forKey: .shipSymbol)
    }
}

